"""Models for local-LLM content optimization suggestions."""
from datetime import datetime
import enum
import uuid

from sqlalchemy import Column, DateTime, Enum as SQLEnum, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class ContentOptimizationRunStatus(str, enum.Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class ContentOptimizationSuggestionType(str, enum.Enum):
    seo_title = "seo_title"
    meta_description = "meta_description"
    h1 = "h1"
    headings = "headings"
    faq = "faq"
    schema = "schema"
    content_refresh = "content_refresh"
    answer_block = "answer_block"
    internal_link_context = "internal_link_context"


class ContentOptimizationSuggestionStatus(str, enum.Enum):
    suggested = "suggested"
    approved = "approved"
    rejected = "rejected"
    applied = "applied"


class ContentOptimizationRun(Base):
    """A local Ollama content optimization generation run for a crawl."""

    __tablename__ = "content_optimization_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    crawl_id = Column(UUID(as_uuid=True), ForeignKey("crawl_jobs.id"), nullable=False, index=True)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=True, index=True)
    tenant_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    status = Column(
        SQLEnum(ContentOptimizationRunStatus),
        default=ContentOptimizationRunStatus.pending,
        nullable=False,
        index=True,
    )
    progress = Column(Integer, default=0)
    model = Column(String(255), nullable=False)
    total_pages = Column(Integer, default=0)
    total_suggestions = Column(Integer, default=0)
    error_message = Column(Text, nullable=True)

    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    suggestions = relationship(
        "ContentOptimizationSuggestion",
        back_populates="run",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        Index("ix_content_opt_runs_tenant_crawl", "tenant_id", "crawl_id"),
        Index("ix_content_opt_runs_created", "created_at", postgresql_using="brin"),
    )


class ContentOptimizationSuggestion(Base):
    """A page-level optimization suggestion generated by deterministic rules and local Ollama."""

    __tablename__ = "content_optimization_suggestions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey("content_optimization_runs.id"), nullable=False, index=True)
    tenant_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=True, index=True)
    crawl_id = Column(UUID(as_uuid=True), ForeignKey("crawl_jobs.id"), nullable=False, index=True)
    page_id = Column(UUID(as_uuid=True), ForeignKey("crawl_pages.id"), nullable=False, index=True)

    suggestion_type = Column(SQLEnum(ContentOptimizationSuggestionType), nullable=False, index=True)
    current_value = Column(Text, nullable=True)
    suggested_value = Column(Text, nullable=False)
    reason = Column(Text, nullable=False)
    priority_score = Column(Float, nullable=False)
    confidence_score = Column(Float, nullable=False)
    status = Column(
        SQLEnum(ContentOptimizationSuggestionStatus),
        default=ContentOptimizationSuggestionStatus.suggested,
        nullable=False,
        index=True,
    )
    content_hash = Column(String(64), nullable=False, index=True)
    evidence = Column(JSONB, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    approved_at = Column(DateTime, nullable=True)
    rejected_at = Column(DateTime, nullable=True)
    applied_at = Column(DateTime, nullable=True)

    run = relationship("ContentOptimizationRun", back_populates="suggestions")

    __table_args__ = (
        Index("ix_content_opt_suggestions_tenant_crawl", "tenant_id", "crawl_id"),
        Index("ix_content_opt_suggestions_page_type", "page_id", "suggestion_type"),
        Index(
            "ix_content_opt_suggestions_dedupe",
            "tenant_id",
            "crawl_id",
            "page_id",
            "suggestion_type",
            "content_hash",
            unique=True,
        ),
        Index("ix_content_opt_suggestions_priority", "priority_score"),
    )
